### ISSUE TITLE
Stack overflow when trying to identify leave-one-out-connected set

### ISSUE THREAD

**Issue by MartinFriedrich93** [tlamadon/bipartitepandas#14]
Dear developers, 

First of all, thank you for supplying the great BipartitePandas and PyTwoWay packages. 

I have an issue identifying the leave-one-out-connected set using BipartitePandas. 

Everything works well on small simulated and test data. However, if I apply the data cleaning to real admin data (>21 Mio. worker-year obs.), Python crashes. The error I get is ‘Windows fatal exception: stack overflow’. A window pops up saying “Python has stopped working” and the Python kernel in Spyder restarts.   

The server I use runs on a Windows 64-bit OS. It has got a 2.1 GHz processor and 256GB RAM. Python uses only about 10GB RAM at max while my program is running. The Python version installed on this server is 3.8.8 and BipartitePandas is version 1.0.35. 

I tried increasing both the stack size and recursion depth (see code in txt file). This did not resolve the problem though. 

I would be grateful if you have any idea what may cause the stack overflow and how to fix it. Please find my code and associated output from the Spyder console below. (I redacted some paths from these files for security reasons.)  

Best
Martin  

[22_8_22_bp_tw_code.txt](https://github.com/tlamadon/bipartitepandas/files/9395252/22_8_22_bp_tw_code.txt)
[output_console.txt](https://github.com/tlamadon/bipartitepandas/files/9395177/output_console.txt)

**Comment by adamoppenheimer** [comment]
Hi Martin,

Here's what I figured out:

-The issue is being caused by a particular method (`.bridges()`) from the package igraph, which is used for estimating the articulation points of the graph. Luckily `.bridges()` is used only for collapsed format data.

-Taking advantage of the fact that the leave-one-out code doesn't rely on this method for long format data, if you estimate the leave-out-match set, but specify `collapse_at_connectedness_measure=False`, then collapse after, it may work. When I tried it on my computer, this worked with large datasets I simulated that wouldn't work with `collapse_at_connectedness_measure=True`.

Please let me know if this works for you!

Best,
Adam

**Comment by MartinFriedrich93** [comment]
Hi Adam, 

Thank you so much for your quick help. The method that you suggested solved the issue. My program just finished without any errors.

Best
Martin
